name: CD

on:
  push:
    branches:
      - main  # Ejecuta en cada push a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up GCP credentials
      run: |
        echo "${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}" | base64 --decode > ${{ github.workspace }}/gcp-key.json
        gcloud auth activate-service-account --key-file ${{ github.workspace }}/gcp-key.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}


    - name: Print Variables
      run: |
        echo "Project ID: ${{ secrets.GCP_PROJECT_ID }}"
        echo "Image Name: ${{ secrets.IMAGE_NAME }}"


    - name: Deploy to Cloud Run
      run: |
          gcloud run deploy ${{ secrets.SERVICE_NAME }} \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.IMAGE_NAME }} \
            --platform managed \
            --region ${{ secrets.CLOUD_RUN_REGION }} \
            --allow-unauthenticated
